@base_url = http://localhost:5008

### User Register
POST {{base_url}}/api/register
Content-Type: application/json

{
    "username": "Shahidul223",
    "email": "shahidul2@gmail.com",
    "password": "Password@123",
    "confirmPassword": "Password@123"
}
### Login user
POST {{base_url}}/api/login
Content-Type: application/json

{
    "userNameOrEmail": "Shahidul223",
    "password": "Password@123"
}